ok4

diff --git a/.github/workflows/auto_rebase_all.yml b/.github/workflows/auto_rebase_all.yml
--- a/.github/workflows/auto_rebase_all.yml
+++ b/.github/workflows/auto_rebase_all.yml
@@ -71,9 +71,9 @@ jobs:
            git config --local user.email "noelkev0@gmail.com" &&  git config --local user.name "arita37"
            git config --global hub.protocol ssh
            # aniket,alex,tranchung,adev01,zdocs_y23487teg65f6,dhamani,bishwa-bk,anhdang
-           bin/hub pull-request --base arita37:main    --head arita37:aniket     -m "PR into main"  || echo "failed"
-           bin/hub pull-request --base arita37:main    --head arita37:anhdang    -m "PR into main"  || echo "failed"
-           bin/hub pull-request --base arita37:main    --head arita37:bishwa-bk  -m "PR into main"  || echo "failed"
+           echo 'aniket'    && bin/hub pull-request --base arita37:main    --head arita37:aniket      -m "PR into main"  || echo "failed"
+           echo 'anhdang'   &&  bin/hub pull-request --base arita37:main    --head arita37:anhdang    -m "PR into main"  || echo "failed"
+           echo 'bishwa-bk' &&  bin/hub pull-request --base arita37:main    --head arita37:bishwa-bk  -m "PR into main"  || echo "failed"
 
 
 
